name: Docs Run

on:
  workflow_dispatch:

jobs:
  generate-and-publish-javadoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Generate Javadoc in fs-all module
        run: gradle :fs-all:javadoc

      # Clone the target repository
      - name: Clone fs-docs repository
        uses: actions/checkout@v4
        with:
          repository: fredsuvn/fs-docs
          ref: repo/fs
          token: ${{ secrets.GITHUB_TOKEN }}
          path: fs-docs

      # Clear the existing javadoc directory
      - name: Clear existing javadoc directory
        run: rm -rf fs-docs/docs/fs/javadoc/*

      # Copy generated javadoc to target directory
      - name: Copy javadoc to target directory
        run: cp -r fs-all/build/docs/javadoc/* fs-docs/docs/fs/javadoc/

      - name: Configure Git
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      # Commit changes to fs-docs repository
      - name: Commit and push javadoc to fs-docs
        run: |
          cd fs-docs
          git add docs/fs/javadoc/
          git commit -m 'Update Javadoc from fs-all module'
          git push origin repo/fs

      # Merge repo/fs branch into main branch
      - name: Merge repo/fs into main
        run: |
          cd fs-docs
          git checkout main
          git merge --no-ff repo/fs -m 'Merge repo/fs into main - Update Javadoc'
          git push origin main