name: JMH Run

on:
  workflow_dispatch:

jobs:
  jmh-benchmarks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Using Gradle rather than ./gradlew
      #- name: Make Gradle wrapper executable
      #  run: chmod +x ./gradlew

      #- name: Verify Gradle wrapper
      #  run: ls -la ./gradlew

      #- name: Check if gradlew exists
      #  run: test -f ./gradlew && echo "gradlew exists" || echo "gradlew not found"

      #- name: Clean fs-core module
      #  run: gradle :fs-core:clean

      - name: Run JMH benchmarks
        run: gradle :fs-tests:jmh

      - name: Copy results to docs directory with timestamp and update main results.json
        run: |
          mkdir -p docs/jmh
          cp fs-tests/build/results/jmh/results.json docs/jmh/results.json

      - name: Configure Git
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Commit and push results
        run: |
          git add docs/jmh/results.json
          git commit -m 'Run jmh-run.yml and update JMH benchmark results via GitHub Actions'
          git push origin HEAD:${{ github.ref_name }}

      # Clone the target repository
      - name: Clone fs-docs repository
        uses: actions/checkout@v4
        with:
          repository: fredsuvn/fs-docs
          ref: main
          token: ${{ secrets.FS_DOCS_PAT }}
          path: fs-docs

      # Create target jmh directory if it doesn't exist
      - name: Create jmh directory
        run: |
          mkdir -p fs-docs/docs/fs/jmh/
          cp fs-tests/build/results/jmh/results.json fs-docs/docs/fs/jmh/results.json

      # Commit changes to fs-docs repository
      - name: Commit and push results.json to fs-docs:main branch
        run: |
          cd fs-docs
          git remote set-url origin https://x-access-token:${{ secrets.FS_DOCS_PAT }}@github.com/fredsuvn/fs-docs.git
          git add docs/fs/jmh/results.json
          git commit -m 'Update jmh results.json from fs-all module'
          git push origin main